const Post = require('../models/Post');
const path = require('path');
const fs = require('fs');

// READ: Get all posts for the logged-in user (Dashboard)
exports.getDashboard = async (req, res) => {
    try {
        // Find posts by this user and populate the 'author' 
        const posts = await Post.find({ author: req.session.user.id })
                                .populate('author', 'username')
                                .sort({ createdAt: -1 }); // Newest first
        res.render('dashboard', { posts, error: null });
    } catch (error) {
        console.error(error);
        res.status(500).send('Server Error');
    }
};

// CREATE: Render the create post form
exports.getCreatePost = (req, res) => {
    res.render('create-post', { error: null });
};

// CREATE: Handle the form submission and image upload
exports.postCreatePost = async (req, res) => {
    try {
        const { title, content } = req.body;
        let imagePath = '';

        // Validate and handle image upload
        if (req.files && req.files.image) {
            const image = req.files.image;
            
            // Check if the uploaded file is actually an image
            if (!image.mimetype.startsWith('image/')) {
                return res.render('create-post', { error: 'Invalid file type. Please upload an image.' });
            }

            // Create a unique filename and set the upload path
            const imageName = Date.now() + '-' + image.name.replace(/\s+/g, '-');
            const uploadPath = path.join(__dirname, '../public/uploads', imageName);
            
            // Move the file to our public/uploads directory
            await image.mv(uploadPath);
            imagePath = '/uploads/' + imageName;
        }

        // Save post to database
        const newPost = new Post({
            title,
            content, // This will be the HTML generated by Quill.js
            image: imagePath,
            author: req.session.user.id
        });

        await newPost.save();
        res.redirect('/dashboard');

    } catch (error) {
        console.error(error);
        res.render('create-post', { error: 'Something went wrong creating the post.' });
    }
};

// DELETE: Handle post deletion
exports.deletePost = async (req, res) => {
    try {
        const post = await Post.findOne({ _id: req.params.id, author: req.session.user.id });
        
        if (!post) {
            return res.status(404).send('Post not found or unauthorized');
        }

        // If the post has an image, delete it from the server
        if (post.image) {
            const imagePath = path.join(__dirname, '../public', post.image);
            if (fs.existsSync(imagePath)) {
                fs.unlinkSync(imagePath);
            }
        }

        await Post.findByIdAndDelete(req.params.id);
        res.redirect('/dashboard');
    } catch (error) {
        console.error(error);
        res.status(500).send('Server Error');
    }
};

// UPDATE: Render the edit post form
exports.getEditPost = async (req, res) => {
    try {
        // Find the post and ensure it belongs to the logged-in user
        const post = await Post.findOne({ _id: req.params.id, author: req.session.user.id });
        
        if (!post) {
            return res.status(404).send('Post not found or unauthorized');
        }
        
        res.render('edit-post', { post, error: null });
    } catch (error) {
        console.error(error);
        res.status(500).send('Server Error');
    }
};

// UPDATE: Handle the form submission and optional new image
exports.postEditPost = async (req, res) => {
    try {
        const { title, content } = req.body;
        const post = await Post.findOne({ _id: req.params.id, author: req.session.user.id });

        if (!post) {
            return res.status(404).send('Post not found or unauthorized');
        }

        // Update basic text fields
        post.title = title;
        post.content = content;

        // Handle new image upload if provided
        if (req.files && req.files.image) {
            const image = req.files.image;
            
            if (!image.mimetype.startsWith('image/')) {
                return res.render('edit-post', { post, error: 'Invalid file type. Please upload an image.' });
            }

            // Delete the old image from the server to save space
            if (post.image) {
                const oldImagePath = path.join(__dirname, '../public', post.image);
                if (fs.existsSync(oldImagePath)) {
                    fs.unlinkSync(oldImagePath);
                }
            }

            // Save the new image
            const imageName = Date.now() + '-' + image.name.replace(/\s+/g, '-');
            const uploadPath = path.join(__dirname, '../public/uploads', imageName);
            
            await image.mv(uploadPath);
            post.image = '/uploads/' + imageName;
        }

        // Save the updated post to MongoDB
        await post.save();
        res.redirect('/dashboard');

    } catch (error) {
        console.error(error);
        res.status(500).send('Server Error');
    }
};

// READ: Get a single full post
exports.getSinglePost = async (req, res) => {
    try {
        const post = await Post.findById(req.params.id).populate('author', 'username');
        
        if (!post) {
            return res.status(404).send('Post not found');
        }
        
        res.render('single-post', { post });
    } catch (error) {
        console.error(error);
        res.status(500).send('Server Error');
    }
};